### PR TITLE
Add ability to upload images and videos

### LINKED ISSUE #3: Add ability to upload images and videos
Currently, the Node SDK only allows for uploading documents. This means that when uploading images and videos, they are currently stored as VANTIQ Documents.

This enhancement would enable the SDK to upload images and videos as VANTIQ Images/Videos, instead of only being able to upload them as documents.

### PR DESCRIPTION
**Pull request by namirfa**
Closes #3 

I could not figure out how to get the intgtests to run since the README is so out of date. I commented out my tests there, but I expect they would pass if I could figure out how to run the test.

I did not add the new upload features to the vantiq-client, but I can try to get this to work.

All other tests pass successfully.

### CODE REVIEW

**Comment by namirfa** [comment]
Just saw that the checks failed, I think it has to do with updating the dependencies to fix the security issues.

**Comment by rblumer4** [comment]
@namirfa, I was able to get most of the intgTests to run, with a couple tweaks.
```
  13 passing (2s)
  2 pending
  2 failing
```
This was in master, not your branch.
I can show you what I did on Monday & maybe we can get the rest to run, too.

**Comment by namirfa** [comment]
@rblumer4 
Thanks Roger! I can sit down with you on Monday and go through how to get those tests running, and then I will tweak the others to make sure everything passes.

**Comment by namirfa** [comment]
Cleaned up all of the tests so that everything passes now. The Travis CI build is failing because I upgraded the node modules to get rid of security issues. 

@rblumer4 Do you have any recommendation on what I can do about the Travis CI build? Looks like the updated node packages are not compatible with node v5, but I think prioritizing security is probably more important than supporting such an old version of node.

**Pull request merged**
